// generated by o3-high-mini
use wrappers::parsers::Parsable;
use std::rc::Rc;
use std::any::Any;
use serde::{Deserialize, Serialize};

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct FallocateAttrs {
    pub fd: i32,
    pub mode: String,
    pub offset: i64,
    pub len: i64,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for FallocateAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = FallocateAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 4 {
            return Err("Invalid arguments for fallocate".into());
        }
        attrs.fd = parts[0].parse().map_err(|e| format!("Failed to parse fd: {}", e))?;
        attrs.mode = parts[1].to_string();
        attrs.offset = parts[2].parse().map_err(|e| format!("Failed to parse offset: {}", e))?;
        attrs.len = parts[3].parse().map_err(|e| format!("Failed to parse len: {}", e))?;
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
