// generated by o3-high-mini
use wrappers::parsers::Parsable;
use std::rc::Rc;
use std::any::Any;
use serde::{Deserialize, Serialize};

#[derive(Default, Debug)]
pub struct FanotifyInitAttrs {
    pub flags: String,
    pub event_f_flags: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for FanotifyInitAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = FanotifyInitAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 2 {
            return Err("Invalid arguments for fanotify_init".into());
        }
        attrs.flags = parts[0].to_string();
        attrs.event_f_flags = parts[1].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
