// generated by o3-high-mini
use wrappers::parsers::Parsable;
use std::rc::Rc;
use std::any::Any;
use serde::{Deserialize, Serialize};

#[derive(Default, Debug)]
pub struct FanotifyMarkAttrs {
    pub fanotify_fd: i32,
    pub flags: String,
    pub mask: String,
    pub fd: i32,
    pub pathname: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for FanotifyMarkAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = FanotifyMarkAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 5 {
            return Err("Invalid arguments for fanotify_mark".into());
        }
        attrs.fanotify_fd = parts[0].parse().map_err(|e| format!("Failed to parse fanotify_fd: {}", e))?;
        attrs.flags = parts[1].to_string();
        attrs.mask = parts[2].to_string();
        attrs.fd = parts[3].parse().map_err(|e| format!("Failed to parse fd: {}", e))?;
        attrs.pathname = parts[4].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
