// generated by o3-high-mini
use wrappers::parsers::Parsable;
use std::rc::Rc;
use std::any::Any;
use serde::{Deserialize, Serialize};

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct FgetxattrAttrs {
    pub path: String,
    pub name: String,
    pub value: String,
    pub size: usize,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for FgetxattrAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = FgetxattrAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 4 {
            return Err("Invalid arguments for fgetxattr".into());
        }
        attrs.path = parts[0].to_string();
        attrs.name = parts[1].to_string();
        attrs.value = parts[2].to_string();
        attrs.size = parts[3].parse().map_err(|e| format!("Failed to parse size: {}", e))?;
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
