// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct FutexWakeAttrs {
    pub uaddr: String,
    pub val: i32,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for FutexWakeAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = FutexWakeAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 2 {
            return Err("Invalid arguments for futex_wake".into());
        }
        attrs.uaddr = parts[0].to_string();
        attrs.val = parts[1].parse().map_err(|e| format!("Failed to parse val: {}", e))?;
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
