// generated by o3-high-mini
use wrappers::parsers::Parsable;
use std::rc::Rc;
use std::any::Any;
use serde::{Deserialize, Serialize};

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct FutexAttrs {
    pub uaddr: String,
    pub futex_op: String,
    pub val: i32,
    pub timeout: Option<String>,
    pub uaddr2: Option<String>,
    pub val3: i32,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for FutexAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = FutexAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 3 {
            return Err("Invalid arguments for futex".into());
        }
        attrs.uaddr = parts[0].to_string();
        attrs.futex_op = parts[1].to_string();
        attrs.val = parts[2].parse().map_err(|e| format!("Failed to parse val: {}", e))?;
        if parts.len() > 3 {
            attrs.timeout = Some(parts[3].to_string());
        }
        if parts.len() > 4 {
            attrs.uaddr2 = Some(parts[4].to_string());
        }
        if parts.len() > 5 {
            attrs.val3 = parts[5].parse().unwrap_or(0);
        }
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
