// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct GetrandomAttrs {
    pub buf: String,
    pub count: usize,
    pub flags: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for GetrandomAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = GetrandomAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 3 {
            return Err("Invalid arguments for getrandom".into());
        }
        attrs.buf = parts[0].to_string();
        attrs.count = parts[1].parse().map_err(|e| format!("Failed to parse count: {}", e))?;
        attrs.flags = parts[2].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
