// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct InotifyInitAttrs {
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for InotifyInitAttrs {
    fn parse(_args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = InotifyInitAttrs::default();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
