// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct LseekAttrs {
    pub fd: i32,
    pub offset: i64,
    pub whence: String,
    pub ret: i64,
}

#[typetag::serde]
impl Parsable for LseekAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = LseekAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 3 {
            return Err("Invalid arguments for lseek".into());
        }
        attrs.fd = parts[0].parse().map_err(|e| format!("Failed to parse fd: {}", e))?;
        attrs.offset = parts[1].parse().map_err(|e| format!("Failed to parse offset: {}", e))?;
        attrs.whence = parts[2].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
