// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;
use helpers::helpers::split_fd_parts;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct LseekAttrs {
    pub fd: i32,
    pub file_name: String,
    pub offset: i64,
    pub whence: String,
    pub ret: i64,
}

#[typetag::serde]
impl Parsable for LseekAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = LseekAttrs::default();

        let parts: Vec<String> = args
        .chars()
        .filter(|&c| !r#""\"? "#.contains(c))
        .collect::<String>()
        .split(',')
        .map(str::to_string)
        .collect::<Vec<String>>();

        if parts.len() < 3 {
            return Err("Invalid arguments for lseek".into());
        }


        let (fd, file_name) = split_fd_parts(&parts[0]);
        attrs.fd = fd;
        attrs.file_name = file_name;

        attrs.offset = parts[1].parse().map_err(|e| format!("Failed to parse offset: {}", e))?;
        attrs.whence = parts[2].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
