// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct NewfstatatAttrs {
    pub dirfd: String,
    pub pathname: String,
    pub statbuf: String,
    pub flags: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for NewfstatatAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = NewfstatatAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 4 {
            return Err("Invalid arguments for newfstatat".into());
        }
        attrs.dirfd = parts[0].to_string();
        attrs.pathname = parts[1].to_string();
        attrs.statbuf = parts[2].to_string();
        attrs.flags = parts[3].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
