// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;


#[derive(Default, Debug, Deserialize, Serialize)]
pub struct PpollAttrs {
    pub fds: String,
    pub nfds: usize,
    pub timeout: String,
    pub sigmask: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for PpollAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = PpollAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 4 {
            return Err("Invalid arguments for ppoll".into());
        }
        attrs.fds = parts[0].to_string();
        attrs.nfds = parts[1].parse().map_err(|e| format!("Failed to parse nfds: {}", e))?;
        attrs.timeout = parts[2].to_string();
        attrs.sigmask = parts[3].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
