// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct PrctlAttrs {
    pub option: String,
    pub arg2: Option<String>,
    pub arg3: Option<String>,
    pub arg4: Option<String>,
    pub arg5: Option<String>,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for PrctlAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = PrctlAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.is_empty() {
            return Err("Invalid arguments for prctl".into());
        }
        attrs.option = parts[0].to_string();
        if parts.len() > 1 { attrs.arg2 = Some(parts[1].to_string()); }
        if parts.len() > 2 { attrs.arg3 = Some(parts[2].to_string()); }
        if parts.len() > 3 { attrs.arg4 = Some(parts[3].to_string()); }
        if parts.len() > 4 { attrs.arg5 = Some(parts[4].to_string()); }
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
