// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct RseqAttrs {
    pub rseq: String,
    pub rseq_len: usize,
    pub flags: String,
    pub sig: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for RseqAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = RseqAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 4 {
            return Err("Invalid arguments for rseq".into());
        }
        attrs.rseq = parts[0].to_string();
        attrs.rseq_len = parts[1].parse().map_err(|e| format!("Failed to parse rseq_len: {}", e))?;
        attrs.flags = parts[2].to_string();
        attrs.sig = parts[3].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
