// generated by o3-high-mini
use wrappers::parsers::Parsable;
use serde::{Deserialize, Serialize};
use std::rc::Rc;
use std::any::Any;

#[derive(Default, Debug, Deserialize, Serialize)]
pub struct WaitidAttrs {
    pub idtype: String,
    pub id: i32,
    pub infop: String,
    pub options: String,
    pub ret: i32,
}

#[typetag::serde]
impl Parsable for WaitidAttrs {
    fn parse(args: &str, result: Option<&str>) -> Result<Self, String> {
        let mut attrs = WaitidAttrs::default();
        let parts: Vec<&str> = args.split(',').map(|s| s.trim()).collect();
        if parts.len() < 4 {
            return Err("Invalid arguments for waitid".into());
        }
        attrs.idtype = parts[0].to_string();
        attrs.id = parts[1].parse().map_err(|e| format!("Failed to parse id: {}", e))?;
        attrs.infop = parts[2].to_string();
        attrs.options = parts[3].to_string();
        if let Some(r) = result {
            attrs.ret = r.trim().parse().unwrap_or(0);
        }
        Ok(attrs)
    }
    
    fn as_any(self: Rc<Self>) -> Rc<dyn Any> {
        self
    }
}
