apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 1
  labels:
    ipfailover: hello-elastic
  name: keepal-elastic
spec:
  replicas: 2
  selector:
    matchLabels:
      ipfailover: hello-elastic
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ipfailover: hello-elastic
    spec:
      containers:
      - env:
        - name: OPENSHIFT_HA_CONFIG_NAME
          value: ipfailover
        - name: OPENSHIFT_HA_VIRTUAL_IPS
          value: 10.1.16.140
        - name: OPENSHIFT_HA_VIP_GROUPS
          value: "140"
        - name: OPENSHIFT_HA_NETWORK_INTERFACE
          value: br-ex
        - name: OPENSHIFT_HA_MONITOR_PORT
          value: "30060"
        - name: OPENSHIFT_HA_VRRP_ID_OFFSET
          value: "0"
        - name: OPENSHIFT_HA_REPLICA_COUNT
          value: "2"
        - name: OPENSHIFT_HA_USE_UNICAST
          value: "false"
        - name: OPENSHIFT_HA_IPTABLES_CHAIN
          value: INPUT
        - name: OPENSHIFT_HA_CHECK_SCRIPT
          value: /usr/bin/true
        - name: OPENSHIFT_HA_PREEMPTION
          value: preempt_delay 300
        - name: OPENSHIFT_HA_CHECK_INTERVAL
          value: "2"
        image: quay.io/openshift/origin-keepalived-ipfailover
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - pgrep
            - keepalived
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: openshift-ipfailover
        ports:
        - containerPort: 61114
          hostPort: 61114
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /host
          mountPropagation: HostToContainer
          name: host-slash
          readOnly: true
        - mountPath: /etc/sysconfig
          name: etc-sysconfig
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/role: gateway
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ipfailover
      serviceAccountName: ipfailover
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /
          type: ""
        name: host-slash
      - hostPath:
          path: /etc/sysconfig
          type: ""
        name: etc-sysconfig
